
const HANDLER_IDS = {

  //회원 가입 및 로그인
  REGISTER_REQUEST: 1,
  REGISTER_RESPONSE: 2,
  LOGIN_REQUEST: 3,
  LOGIN_RESPONSE: 4,

  // 방 생성
  CREATE_ROOM_REQUEST: 5,
  CREATE_ROOM_RESPONSE: 6,

  // 방 목록 조회
  GET_ROOM_LIST_REQUEST: 7,
  GET_ROOM_LIST_RESPONSE: 8,

  // 방 참가
  JOIN_ROOM_REQUEST: 9,
  JOIN_ROOM_RESPONSE: 10,

  // 랜덤 방 참가
  JOIN_RANDOM_ROOM_REQUEST: 11,
  JOIN_RANDOM_ROOM_RESPONSE: 12,

  // 방 참가 알림
  JOIN_ROOM_NOTIFICATION: 13,

  // 방 나가기
  LEAVE_ROOM_REQUEST: 14,
  LEAVE_ROOM_RESPONSE: 15,

  // 방 나가기 알림
  LEAVE_ROOM_NOTIFICATION: 16,

  // 게임 준비
  GAME_PREPARE_REQUEST: 17,
  GAME_PREPARE_RESPONSE: 18,
  GAME_PREPARE_NOTIFICATION: 19,

  // 게임 시작
  GAME_START_REQUEST: 20,
  GAME_START_RESPONSE: 21,
  GAME_START_NOTIFICATION: 22,

  // 위치 업데이트
  POSITION_UPDATE_REQUEST: 23,
  POSITION_UPDATE_NOTIFICATION: 24,

  // 카드 사용
  USE_CARD_REQUEST: 25,
  USE_CARD_RESPONSE: 26,

  // 카드 효과 알림
  USE_CARD_NOTIFICATION: 27,
  EQUIP_CARD_NOTIFICATION: 28,
  CARD_EFFECT_NOTIFICATION: 29,

  // 플리마켓
  FLEA_MARKET_NOTIFICATION: 30,
  FLEA_MARKET_PICK_REQUEST: 31,
  FLEA_MARKET_PICK_RESPONSE: 32,

  // 유저 정보 업데이트
  USER_UPDATE_NOTIFICATION: 33,

  // 페이즈 업데이트
  PHASE_UPDATE_NOTIFICATION: 34,

  // 리액션
  REACTION_REQUEST: 35,
  REACTION_RESPONSE: 36,

  // 카드 버리기
  DESTROY_CARD_REQUEST: 37,
  DESTROY_CARD_RESPONSE: 38,

  // 게임 종료
  GAME_END_NOTIFICATION: 39,

  // 카드 선택
  CARD_SELECT_REQUEST: 40,
  CARD_SELECT_RESPONSE: 41,

  // 디버프 넘기기
  PASS_DEBUFF_REQUEST: 42,
  PASS_DEBUFF_RESPONSE: 43,
  WARNING_NOTIFICATION: 44,

  // 효과 알림
  ANIMATION_NOTIFICATION: 45,

  REGISTER: 1,
  LOGIN: 3,

};

export default HANDLER_IDS;
