const PACKET_TYPE_LENGTH = 2;
const VERSION_LENGTH = 1;
const SEQUENCE_LENGTH = 4;
const PAYLOAD_LENGTH = 4;
const VERSION = 5;
export const TOTAL_LENGTH =
  PACKET_TYPE_LENGTH + VERSION_LENGTH + SEQUENCE_LENGTH + PAYLOAD_LENGTH + VERSION;
export const HEADER = {
  PACKET_TYPES_LENGTH: 2,
  VERSION_LENGTH: 1,
  SEQUENCE_LENGTH: 4,
  PAYLOAD_LENGTH: 4,
};
