CREATE TABLE IF NOT EXISTS sqlUsers (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name_id VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);